TESTS = [
  ["Positioning", [
    # ["pos","position: ;"],
    ["poss","position: static;"],
    ["posa","position: absolute;"],
    ["posr","position: relative;"],
    ["posf","position: fixed;"],
    ["t","top: ;"],
    ["ta","top: auto;"],
    ["r","right: ;"],
    ["ra","right: auto;"],
    ["b","bottom: ;"],
    ["ba","bottom: auto;"],
    ["l","left: ;"],
    ["la","left: auto;"],
    ["z","z-index: ;"],
    ["za","z-index: auto;"],
  ]],

  ["Box behavior and properties", [
    # ["fl","float: ;"],
    ["fln","float: none;"],
    ["fll","float: left;"],
    ["flr","float: right;"],
    # ["cl","clear: ;"],
    ["cln","clear: none;"],
    ["cll","clear: left;"],
    ["clr","clear: right;"],
    ["clb","clear: both;"],
    ["d","display: ;"],
    ["dn","display: none;"],
    ["db","display: block;"],
    ["di","display: inline;"],
    ["dib","display: inline-block;"],
    ["dli","display: list-item;"],
    ["dri","display: run-in;"],
    ["dcp","display: compact;"],
    ["dtb","display: table;"],
    ["ditb","display: inline-table;"],
    ["dtbcp","display: table-caption;"],
    ["dtbcl","display: table-column;"],
    ["dtbclg","display: table-column-group;"],
    ["dtbhg","display: table-header-group;"],
    ["dtbfg","display: table-footer-group;"],
    ["dtbr","display: table-row;"],
    ["dtbrg","display: table-row-group;"],
    ["dtbc","display: table-cell;"],
    ["v","visibility: ;"],
    ["vv","visibility: visible;"],
    ["vh","visibility: hidden;"],
    ["vc","visibility: collapse;"],
    # ["ov","overflow: ;"],
    ["ovv","overflow: visible;"],
    ["ovh","overflow: hidden;"],
    ["ovs","overflow: scroll;"],
    ["ova","overflow: auto;"],
    ["ovx","overflow-x: ;"],
    ["ovxv","overflow-x: visible;"],
    ["ovxh","overflow-x: hidden;"],
    ["ovxs","overflow-x: scroll;"],
    ["ovxa","overflow-x: auto;"],
    ["ovy","overflow-y: ;"],
    ["ovyv","overflow-y: visible;"],
    ["ovyh","overflow-y: hidden;"],
    ["ovys","overflow-y: scroll;"],
    ["ovya","overflow-y: auto;"],
    ["ovst","overflow-style: ;"],
    ["ovsa","overflow-style: auto;"],
    ["ovss","overflow-style: scrollbar;"],
    ["ovsp","overflow-style: panner;"],
    ["ovsm","overflow-style: move;"],
    ["ovsmq","overflow-style: marquee;"],
    # ["zoo","zoom: 1;"],
    ["cp","clip: ;"],
    ["cpa","clip: auto;"],
    # ["cpr","clip: rect(0 0 0 0);"],
    # ["bxz","box-sizing: ;"], # Find what to do with prefixes
    ["bxzcb","box-sizing: content-box;"],
    ["bxzbb","box-sizing: border-box;"],
    # ["bxsh","box-shadow: ;"], # Find what to do with prefixes, hovewer in zen there is a default to none
    ["bxshn","box-shadow: none;"],
    # ["bxsh+","box-shadow: 0 0 0 #000;"],
    # ["bxshw","-webkit-box-shadow: ;"],
    # ["bxshw+","-webkit-box-shadow: 0 0 0 #000;"],
    # ["bxshm","-moz-box-shadow: ;"],
    # ["bxshm+","-moz-box-shadow: 0 0 0 0 #000;"],
  ]],

  ["Sizing", [
    ["m","margin: ;"],
    ["ma","margin: auto;"],
    # ["m0","margin: 0;"],
    # ["m2","margin: 0 0;"], # In zen there is a multiple 0 0 0, it's overheaded
    # ["m3","margin: 0 0 0;"],
    # ["m4","margin: 0 0 0 0;"],
    ["mt","margin-top: ;"],
    ["mta","margin-top: auto;"],
    ["mr","margin-right: ;"],
    ["mra","margin-right: auto;"],
    ["mb","margin-bottom: ;"],
    ["mba","margin-bottom: auto;"],
    ["ml","margin-left: ;"],
    ["mla","margin-left: auto;"],
    ["p","padding: ;"],
    # ["p0","padding: 0;"],
    # ["p2","padding: 0 0;"], # In zen there is a multiple 0 0 0, it's overheaded
    # ["p3","padding: 0 0 0;"],
    # ["p4","padding: 0 0 0 0;"],
    ["pt","padding-top: ;"],
    ["pr","padding-right: ;"],
    ["pb","padding-bottom: ;"],
    ["pl","padding-left: ;"],
    ["w","width: ;"],
    ["wa","width: auto;"],
    ["h","height: ;"],
    ["ha","height: auto;"],
    ["maw","max-width: ;"],
    ["mawn","max-width: none;"],
    ["mah","max-height: ;"],
    ["mahn","max-height: none;"],
    ["miw","min-width: ;"],
    ["mih","min-height: ;"],
  ]],

  ["Color appearance", [
    # ["o","outline: ;"], # Overflow > Outline!
    # ["on","outline: none;"],
    # ["o+","outline: 1px solid #000;"],
    ["oo","outline-offset: ;"],
    ["ow","outline-width: ;"],
    # ["os","outline-style: ;"],
    # ["oc","outline-color: #000;"],
    # ["oci","outline-color: invert;"],
    ["bd","border: ;"],
    ["bdn","border: none;"],
    # ["bd+","border: 1px solid #000;"],
    ["bdbk","border-break: ;"],
    ["bdbkc","border-break: close;"],
    ["bdcl","border-collapse: ;"],
    ["bdclc","border-collapse: collapse;"],
    ["bdcls","border-collapse: separate;"],
    # ["bdc","border-color: #000;"],
    ["bdi","border-image: ;"],
    ["bdin","border-image: none;"],
    ["bdf","border-fit: ;"],
    ["bdfc","border-fit: clip;"],
    ["bdfr","border-fit: repeat;"],
    ["bdfsc","border-fit: scale;"],
    ["bdfst","border-fit: stretch;"],
    ["bdfow","border-fit: overwrite;"],
    ["bdfof","border-fit: overflow;"],
    ["bdfsp","border-fit: space;"],
    ["bdsp","border-spacing: ;"],
    ["bds","border-style: ;"],
    ["bdsn","border-style: none;"],
    ["bdsh","border-style: hidden;"],
    ["bdsdt","border-style: dotted;"],
    ["bdsds","border-style: dashed;"],
    ["bdss","border-style: solid;"],
    ["bdsdb","border-style: double;"],
    ["bdsdtds","border-style: dot-dash;"],
    ["bdsdtdtds","border-style: dot-dot-dash;"],
    ["bdsw","border-style: wave;"],
    ["bdsg","border-style: groove;"],
    ["bdsr","border-style: ridge;"],
    ["bdsi","border-style: inset;"],
    ["bdso","border-style: outset;"],
    ["bdw","border-width: ;"],
    ["bdt","border-top: ;"],
    ["bdtn","border-top: none;"],
    # ["bdt+","border-top: 1px solid #000;"],
    ["bdtw","border-top-width: ;"],
    ["bdts","border-top-style: ;"],
    ["bdtsn","border-top-style: none;"],
    # ["bdtc","border-top-color: #000;"],
    ["bdr","border-right: ;"],
    ["bdrn","border-right: none;"],
    # ["bdr+","border-right: 1px solid #000;"],
    ["bdrw","border-right-width: ;"],
    ["bdrs","border-right-style: ;"],
    ["bdrsn","border-right-style: none;"],
    # ["bdrc","border-right-color: #000;"],
    ["bdb","border-bottom: ;"],
    ["bdbn","border-bottom: none;"],
    # ["bdb+","border-bottom: 1px solid #000;"],
    ["bdbw","border-bottom-width: ;"],
    ["bdbs","border-bottom-style: ;"],
    ["bdbsn","border-bottom-style: none;"],
    # ["bdbc","border-bottom-color: #000;"],
    ["bdl","border-left: ;"],
    ["bdln","border-left: none;"],
    # ["bdl+","border-left: 1px solid #000;"],
    ["bdlw","border-left-width: ;"],
    ["bdls","border-left-style: ;"],
    ["bdlsn","border-left-style: none;"],
    # ["bdlc","border-left-color: #000;"],
    # ["bdrz","border-radius: ;"], # BRA!
    # ["bdrzw","-webkit-border-radius: ;"],
    # ["bdrzm","-moz-border-radius: ;"],
    # ["bdtrrz","border-top-right-radius: ;"], # Hovewer need topleftrightbottoms
    # ["bdtlrz","border-top-left-radius: ;"],
    # ["bdbrrz","border-bottom-right-radius: ;"],
    # ["bdblrz","border-bottom-left-radius: ;"],
    # ["bg","background: ;"],
    ["bgn","background: none;"], # Error!
    # ["bg+","background: #FFF url() 0 0 no-repeat;"],
    # ["bgie","filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='',sizingMethod='crop');"],
    # ["bgc","background-color: #FFF;"],
    ["bgct","background-color: transparent;"], # Error!
    # ["bgi","background-image: url();"],
    ["bgin","background-image: none;"],
    ["bgr","background-repeat: ;"],
    ["bgrr","background-repeat: repeat;"],
    ["bgrx","background-repeat: repeat-x;"],
    ["bgry","background-repeat: repeat-y;"],
    ["bgrn","background-repeat: no-repeat;"], # Error!
    ["bga","background-attachment: ;"],
    ["bgaf","background-attachment: fixed;"],
    ["bgas","background-attachment: scroll;"],
    # ["bgp","background-position: 0 0;"],
    ["bgpx","background-position-x: ;"],
    ["bgpy","background-position-y: ;"],
    ["bgbk","background-break: ;"],
    ["bgbkbb","background-break: bounding-box;"],
    ["bgbkeb","background-break: each-box;"],
    ["bgbkc","background-break: continuous;"],
    ["bgcp","background-clip: ;"],
    ["bgcpbb","background-clip: border-box;"],
    ["bgcppb","background-clip: padding-box;"],
    ["bgcpcb","background-clip: content-box;"],
    ["bgcpnc","background-clip: no-clip;"],
    ["bgo","background-origin: ;"],
    ["bgopb","background-origin: padding-box;"],
    ["bgobb","background-origin: border-box;"],
    ["bgocb","background-origin: content-box;"],
    # ["bgz","background-size: ;"], # In Zen there is an incorrect abbr
    # ["bgza","background-size: auto;"],
    # ["bgzct","background-size: contain;"],
    # ["bgzcv","background-size: cover;"],
    # ["c","color: #000;"],
  ]],

  ["Special content types", [
    ["tbl","table-layout: ;"],
    ["tbla","table-layout: auto;"],
    ["tblf","table-layout: fixed;"],
    ["cps","caption-side: ;"],
    ["cpst","caption-side: top;"],
    ["cpsb","caption-side: bottom;"],
    ["ec","empty-cells: ;"],
    ["ecs","empty-cells: show;"],
    ["ech","empty-cells: hide;"],
    ["lis","list-style: ;"],
    ["lisn","list-style: none;"],
    ["lisp","list-style-position: ;"],
    ["lispi","list-style-position: inside;"],
    ["lispo","list-style-position: outside;"],
    ["list","list-style-type: ;"],
    ["listn","list-style-type: none;"],
    ["listd","list-style-type: disc;"],
    ["listc","list-style-type: circle;"],
    ["lists","list-style-type: square;"],
    ["listdc","list-style-type: decimal;"],
    ["listdclz","list-style-type: decimal-leading-zero;"],
    ["listlr","list-style-type: lower-roman;"],
    ["listur","list-style-type: upper-roman;"],
    ["lisi","list-style-image: ;"],
    ["lisin","list-style-image: none;"],
    ["q","quotes: ;"],
    ["qn","quotes: none;"],
    # ["qru","quotes: '\00AB' '\00BB' '\201E' '\201C';"],
    # ["qen","quotes: '\201C' '\201D' '\2018' '\2019';"],
    ["ct","content: ;"],
    ["ctn","content: normal;"],
    ["ctoq","content: open-quote;"],
    ["ctnoq","content: no-open-quote;"],
    ["ctcq","content: close-quote;"],
    ["ctncq","content: no-close-quote;"],
    ["cta","content: attr();"],
    ["ctc","content: counter();"],
    ["ctcs","content: counters();"],
    ["coi","counter-increment: ;"],
    ["cor","counter-reset: ;"],
  ]],

  ["Text", [
    ["va","vertical-align: ;"],
    ["vasup","vertical-align: super;"],
    ["vat","vertical-align: top;"],
    ["vatt","vertical-align: text-top;"],
    ["vam","vertical-align: middle;"],
    ["vabl","vertical-align: baseline;"],
    ["vab","vertical-align: bottom;"],
    ["vatb","vertical-align: text-bottom;"],
    ["vasub","vertical-align: sub;"],
    ["ta","text-align: ;"],
    ["tal","text-align: left;"],
    ["tac","text-align: center;"],
    ["tar","text-align: right;"],
    ["taj","text-align: justify;"],
    ["tal","text-align-last: ;"],
    ["tala","text-align-last: auto;"],
    ["tall","text-align-last: left;"],
    ["talc","text-align-last: center;"],
    ["talr","text-align-last: right;"],
    ["td","text-decoration: ;"],
    ["tdn","text-decoration: none;"],
    ["tdo","text-decoration: overline;"],
    ["tdl","text-decoration: line-through;"],
    ["tdu","text-decoration: underline;"],
    ["te","text-emphasis: ;"],
    ["ten","text-emphasis: none;"],
    ["teac","text-emphasis: accent;"],
    ["tedt","text-emphasis: dot;"],
    ["tec","text-emphasis: circle;"],
    ["teds","text-emphasis: disc;"],
    ["teb","text-emphasis: before;"],
    ["tea","text-emphasis: after;"],
    ["th","text-height: ;"],
    ["tha","text-height: auto;"],
    ["thf","text-height: font-size;"],
    ["tht","text-height: text-size;"],
    ["thm","text-height: max-size;"],
    ["ti","text-indent: ;"],
    ["ti-","text-indent: -9999px;"],
    ["tj","text-justify: ;"],
    ["tja","text-justify: auto;"],
    ["tjiw","text-justify: inter-word;"],
    ["tjii","text-justify: inter-ideograph;"],
    ["tjic","text-justify: inter-cluster;"],
    ["tjd","text-justify: distribute;"],
    ["tjk","text-justify: kashida;"],
    ["tjt","text-justify: tibetan;"],
    ["to","text-outline: ;"],
    ["ton","text-outline: none;"],
    # ["to+","text-outline: 0 0 #000;"],
    ["tr","text-replace: ;"],
    ["trn","text-replace: none;"],
    ["tt","text-transform: ;"],
    ["ttn","text-transform: none;"],
    ["ttu","text-transform: uppercase;"],
    ["ttc","text-transform: capitalize;"],
    ["ttl","text-transform: lowercase;"],
    ["tw","text-wrap: ;"],
    ["twn","text-wrap: normal;"],
    ["twno","text-wrap: none;"],
    ["twu","text-wrap: unrestricted;"],
    ["tws","text-wrap: suppress;"],
    ["tsh","text-shadow: ;"],
    ["tshn","text-shadow: none;"],
    # ["tsh+","text-shadow: 0 0 0 #000;"],
    ["lh","line-height: ;"],
    ["whs","white-space: ;"],
    ["whsn","white-space: normal;"],
    ["whsp","white-space: pre;"],
    ["whsnw","white-space: nowrap;"],
    ["whspw","white-space: pre-wrap;"],
    ["whspl","white-space: pre-line;"],
    ["whsc","white-space-collapse: ;"],
    ["whscn","white-space-collapse: normal;"],
    ["whsck","white-space-collapse: keep-all;"],
    ["whscl","white-space-collapse: loose;"],
    ["whscbs","white-space-collapse: break-strict;"],
    ["whscba","white-space-collapse: break-all;"],
    ["wob","word-break: ;"],
    ["wobn","word-break: normal;"],
    ["wobk","word-break: keep-all;"],
    ["wobl","word-break: loose;"],
    ["wobbs","word-break: break-strict;"],
    ["wobba","word-break: break-all;"],
    ["wos","word-spacing: ;"],
    ["wow","word-wrap: ;"],
    ["wown","word-wrap: normal;"],
    ["wowno","word-wrap: none;"],
    ["wowu","word-wrap: unrestricted;"],
    ["wows","word-wrap: suppress;"],
    ["lts","letter-spacing: ;"],
    ["f","font: ;"],
    #["f+","font: 1em Arial,sans-serif;"],
    ["fw","font-weight: ;"],
    ["fwn","font-weight: normal;"],
    ["fwb","font-weight: bold;"],
    ["fwbr","font-weight: bolder;"],
    ["fwlr","font-weight: lighter;"],
    # ["fs","font-style: ;"],
    ["fsn","font-style: normal;"],
    ["fsi","font-style: italic;"],
    ["fso","font-style: oblique;"],
    ["fv","font-variant: ;"],
    ["fvn","font-variant: normal;"],
    ["fvsc","font-variant: small-caps;"],
    ["fz","font-size: ;"],
    # ["fza","font-size-adjust: ;"],
    # ["fzan","font-size-adjust: none;"],
    ["ff","font-family: ;"],
    #["ffs","font-family: Georgia,'Times New Roman',serif;"],
    #["ffss","font-family: Helvetica,Arial,sans-serif;"],
    #["ffc","font-family: 'Monotype Corsiva','Comic Sans MS',cursive;"],
    #["fff","font-family: Capitals,Impact,fantasy;"],
    #["ffm","font-family: Monaco,'Courier New',monospace;"],
    ["fef","font-effect: ;"],
    ["fefn","font-effect: none;"],
    ["fefeg","font-effect: engrave;"],
    ["fefeb","font-effect: emboss;"],
    ["fefo","font-effect: outline;"],
    ["fem","font-emphasize: ;"],
    ["femp","font-emphasize-position: ;"],
    ["fempb","font-emphasize-position: before;"],
    ["fempa","font-emphasize-position: after;"],
    ["fems","font-emphasize-style: ;"],
    ["femsn","font-emphasize-style: none;"],
    ["femsac","font-emphasize-style: accent;"],
    ["femsdt","font-emphasize-style: dot;"],
    ["femsc","font-emphasize-style: circle;"],
    ["femsds","font-emphasize-style: disc;"],
    ["fsm","font-smooth: ;"],
    ["fsma","font-smooth: auto;"],
    ["fsmn","font-smooth: never;"],
    ["fsmaw","font-smooth: always;"],
    # ["fst","font-stretch: ;"],
    # ["fstn","font-stretch: normal;"],
    # ["fstuc","font-stretch: ultra-condensed;"],
    # ["fstec","font-stretch: extra-condensed;"],
    # ["fstc","font-stretch: condensed;"],
    # ["fstsc","font-stretch: semi-condensed;"],
    # ["fstse","font-stretch: semi-expanded;"],
    # ["fste","font-stretch: expanded;"],
    # ["fstee","font-stretch: extra-expanded;"],
    # ["fstue","font-stretch: ultra-expanded;"],
  ]],

  ["Visual properties", [
    ["op","opacity: ;"],
    # ["opie","filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);"],
    # ["opms","-ms-filter: 'progid:DXImageTransform.Microsoft.Alpha(Opacity=100)';"],
    ["rz","resize: ;"],
    ["rzn","resize: none;"],
    ["rzb","resize: both;"],
    ["rzh","resize: horizontal;"],
    ["rzv","resize: vertical;"],
    ["cur","cursor: ;"],
    ["cura","cursor: auto;"],
    ["curd","cursor: default;"],
    ["curc","cursor: crosshair;"],
    ["curha","cursor: hand;"],
    ["curhe","cursor: help;"],
    ["curm","cursor: move;"],
    ["curp","cursor: pointer;"],
    ["curt","cursor: text;"],
  ]],

  ["Print", [
    ["pgbb","page-break-before: ;"],
    ["pgbba","page-break-before: auto;"],
    ["pgbbaw","page-break-before: always;"],
    ["pgbbl","page-break-before: left;"],
    ["pgbbr","page-break-before: right;"],
    ["pgbi","page-break-inside: ;"],
    ["pgbia","page-break-inside: auto;"],
    ["pgbiav","page-break-inside: avoid;"],
    ["pgba","page-break-after: ;"],
    ["pgbaa","page-break-after: auto;"],
    ["pgbaaw","page-break-after: always;"],
    ["pgbal","page-break-after: left;"],
    ["pgbar","page-break-after: right;"],
    ["orp","orphans: ;"],
    ["wid","width: ;"]
  ]]
]